<?php

namespace Bioversity\ServerConnectionBundle\Repository;

class Tags{
   const  kTAG_NID='_id';
   const  kTAG_LID='1';
   const  kTAG_GID='2';
   const  kTAG_UID='3';
   const  kTAG_PID='4';
   const  kTAG_SYNONYMS='5';
   const  kTAG_CATEGORY='6';
   const  kTAG_KIND='7';
   const  kTAG_TYPE='8';
   const  kTAG_CLASS='9';
   const  kTAG_NAMESPACE='10';
   const  kTAG_INPUT='11';
   const  kTAG_PATTERN='12';
   const  kTAG_LENGTH='13';
   const  kTAG_MIN_VAL='14';
   const  kTAG_MAX_VAL='15';
   const  kTAG_NAME='16';
   const  kTAG_LABEL='17';
   const  kTAG_DEFINITION='18';
   const  kTAG_DESCRIPTION='19';
   const  kTAG_NOTES='20';
   const  kTAG_EXAMPLES='21';
   const  kTAG_AUTHORS='22';
   const  kTAG_ACKNOWLEDGMENTS='23';
   const  kTAG_BIBLIOGRAPHY='24';
   const  kTAG_VERSION='25';
   const  kTAG_TERM='26';
   const  kTAG_NODE='27';
   const  kTAG_TAG='28';
   const  kTAG_SUBJECT='29';
   const  kTAG_OBJECT='30';
   const  kTAG_PREDICATE='31';
   const  kTAG_PATH='32';
   const  kTAG_NAMESPACE_REFS='33';
   const  kTAG_NODES='34';
   const  kTAG_EDGES='35';
   const  kTAG_FEATURES='36';
   const  kTAG_METHODS='37';
   const  kTAG_SCALES='38';
   const  kTAG_USER_NAME='39';
   const  kTAG_USER_CODE='40';
   const  kTAG_USER_PASS='41';
   const  kTAG_USER_MAIL='42';
   const  kTAG_USER_ROLE='43';
   const  kTAG_USER_PROFILE='44';
   const  kTAG_USER_MANAGER='45';
   const  kTAG_USER_DOMAIN='46';
   const  kTAG_USER_INSTITUTE_CODE='47';
   const  kTAG_USER_INSTITUTE_NAME='48';
   const  kTAG_USER_INSTITUTE_ADDRESS='49';
   const  kTAG_USER_INSTITUTE_COUNTRY='50';
}