bioversity_attributefields_homepage:
    pattern:  /
    defaults: { _controller: BioversityAttributefieldsBundle:Default:index }
    
bioversity_attributefields_get_attribute:
    pattern:  /get_attribute/{id}/{_locale}.{_format}
    defaults: { _controller: BioversityAttributefieldsBundle:Default:getattribute, _format: json, _locale: en}
    requirements:
      _method:  GET
      _format: JSON
