parameters:
#    bioversity_attributefields.example.class: Bioversity\AttributefieldsBundle\Example

services:
#    bioversity_attributefields.example:
#        class: %bioversity_attributefields.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
