bioversity_dinamic_form:
    resource: "@BioversityDinamicFormBundle/Resources/config/routing.yml"
    prefix:   /

bioversity_trait:
    resource: "@BioversityTraitBundle/Resources/config/routing.yml"
    prefix:   /

bioversity_server_connection:
    resource: "@BioversityServerConnectionBundle/Resources/config/routing.yml"
    prefix:   /

bioversity_site_structure:
    resource: "@BioversitySiteStructureBundle/Resources/config/routing.yml"
    prefix:   /

bioversity_slider:
    resource: "@BioversitySliderBundle/Resources/config/routing.yml"
    prefix:   /

bioversity_ontology:
    resource: "@BioversityOntologyBundle/Resources/config/routing.yml"
    prefix:   /
    
bioversity_security:
    resource: "@BioversitySecurityBundle/Resources/config/routing.yml"
    prefix:   /
    
bioversity_user:
    resource: "@BioversityUserBundle/Resources/config/routing.yml"
    prefix:   /