bioversity_ontology:
    resource: "@BioversityOntologyBundle/Resources/config/routing.yml"
    prefix:   /
    
bioversity_security:
    resource: "@BioversitySecurityBundle/Resources/config/routing.yml"
    prefix:   /
    
bioversity_user:
    resource: "@BioversityUserBundle/Resources/config/routing.yml"
    prefix:   /