jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    firewalls:
        dev:
            pattern:    ^/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                failure_path: /login
            logout:
                path:   /logout
                target: /
                
    encoders:
        Bioversity\SecurityBundle\Repository\User\WebserviceUser: plaintext

    providers:
        webservice:
            id: webservice_user_provider