b_o_homepage:
    pattern:  /
    defaults: { _controller: BioversityOntologyBundle:Default:index }

b_o_user_registration:
    pattern:  /registration
    defaults: { _controller: BioversityOntologyBundle:Default:registration }
    
b_o_contact:
    pattern:  /contact
    defaults: { _controller: BioversityOntologyBundle:Default:contact }

b_o_about:
    pattern:  /about
    defaults: { _controller: BioversityOntologyBundle:Default:about }

b_o_database:
    pattern:  /database
    defaults: { _controller: BioversityOntologyBundle:Default:database }

b_o_browse_landrace:
    pattern:  /browse-landrace
    defaults: { _controller: BioversityOntologyBundle:Default:browseLandrace }

b_o_browse_cwr:
    pattern:  /browse-cwr
    defaults: { _controller: BioversityOntologyBundle:Default:browse_Cwr }

b_o_browse_trait:
    pattern:  /browse-trait
    defaults: { _controller: BioversityOntologyBundle:Default:browseTrait }

b_o_datasets:
    pattern:  /datasets
    defaults: { _controller: BioversityOntologyBundle:Default:datasets }

b_o_data_search:
    pattern:  /data-search
    defaults: { _controller: BioversityOntologyBundle:Default:dataSearch }

b_o_download_data:
    pattern:  /download-data
    defaults: { _controller: BioversityOntologyBundle:Default:downloadData }

b_o_request_data:
    pattern:  /request-data
    defaults: { _controller: BioversityOntologyBundle:Default:requestData }

b_o_contribute_data:
    pattern:  /contribute-data
    defaults: { _controller: BioversityOntologyBundle:Default:contributeData }
    
b_o_browse_slaider:
    pattern:  /browse-slaider
    defaults: { _controller: BioversityOntologyBundle:Default:browseSlaider }

#----------------------------------------------------------------------------
#-----------------------ADMIN AREA-------------------------------------------
#----------------------------------------------------------------------------

b_o_dashboard:
    pattern:  /admin/dashboard
    defaults: { _controller: BioversityOntologyBundle:Default:dashboard }

b_o_edit_profile:
    pattern:  /admin/edit-profile
    defaults: { _controller: BioversityOntologyBundle:Default:editProfile }
