bioversity_ontology_browse_slider:
    pattern:  /ontology/browse-slider
    defaults: { _controller: BioversityOntologyBundle:Ontology:browseSlider }

bioversity_ontology_term_new:
    pattern:  /ontology/term/new
    defaults: { _controller: BioversityOntologyBundle:Ontology:newTerm }
    
bioversity_ontology_namespace_new:
    pattern:  /ontology/namespace/new
    defaults: { _controller: BioversityOntologyBundle:Ontology:newNamespace }

bioversity_ontology_node_new:
    pattern:  /ontology/node/new/{term}
    defaults: { _controller: BioversityOntologyBundle:Ontology:newNode }
    
bioversity_ontology_predicate_new:
    pattern:  /ontology/predicate/new/{node}
    defaults: { _controller: BioversityOntologyBundle:Ontology:newPredicate }    
    
#----------------------------------------------------------------------------
#-----------------------PARTIAL RESPONCE-------------------------------------
#----------------------------------------------------------------------------
bioversity_ontology_partial_term_new:
    pattern:  /ontology/partial/term/new
    defaults: { _controller: BioversityOntologyBundle:Ontology:partialNewTerm }
    
bioversity_ontology_partial_predicate_new:
    pattern:  /ontology/partial/predicate/new/{node}/{direction}
    defaults: { _controller: BioversityOntologyBundle:Ontology:partialNewPredicate }

#----------------------------------------------------------------------------
#-----------------------MODAL RESPONCE---------------------------------------
#---------------------------------------------------------------------------- 
bioversity_ontology_modal_term_new:
    pattern:  /ontology/modal/term/new
    defaults: { _controller: BioversityOntologyBundle:Ontology:modalNewTerm }
    
bioversity_ontology_modal_node_new:
    pattern:  /ontology/modal/node/new/{term}
    defaults: { _controller: BioversityOntologyBundle:Ontology:modalNewNode }
    
bioversity_ontology_modal_namespace_new:
    pattern:  /ontology/modal/namespace/new
    defaults: { _controller: BioversityOntologyBundle:Ontology:modalNewNamespace }
    
bioversity_ontology_modal_predicate_new:
    pattern:  /ontology/modal/predicate/new/{node}
    defaults: { _controller: BioversityOntologyBundle:Ontology:modalNewPredicate }
    
#----------------------------------------------------------------------------
#-----------------------JSON RESPONCE----------------------------------------
#----------------------------------------------------------------------------

bioversity_ontology_json_find_lid:
    pattern:  /ontology/json/find/lid/{lid}/{namespace}
    defaults: { _controller: BioversityOntologyBundle:Ontology:jsonFindLid }

bioversity_ontology_json_find_lid_without_namespace:
    pattern:  /ontology/json/find/lid/{lid}
    defaults: { _controller: BioversityOntologyBundle:Ontology:jsonFindLid }

bioversity_ontology_json_find_namespace:
    pattern:  /ontology/json/find/namespace/{word}
    defaults: { _controller: BioversityOntologyBundle:Ontology:jsonFindNamespace }

bioversity_ontology_json_get_term_with_namespace:
    pattern:  /ontology/json/get/term/{lid}/{namespace}
    defaults: { _controller: BioversityOntologyBundle:Ontology:jsonGetTerm }

bioversity_ontology_json_get_term_without_namespace:
    pattern:  /ontology/json/get/term/{lid}
    defaults: { _controller: BioversityOntologyBundle:Ontology:jsonGetTerm }
    
bioversity_ontology_json_term_new:
    pattern:  /ontology/json/term/new
    defaults: { _controller: BioversityOntologyBundle:Ontology:jsonNewTerm }