b_o_homepage:
    pattern:  /
    defaults: { _controller: BioversityOntologyBundle:Default:index }

b_o_user_registration:
    pattern:  /registration
    defaults: { _controller: BioversityOntologyBundle:Default:registration }
    
b_o_contact:
    pattern:  /contact
    defaults: { _controller: BioversityOntologyBundle:Default:contact }

b_o_about:
    pattern:  /about
    defaults: { _controller: BioversityOntologyBundle:Default:about }

b_o_database:
    pattern:  /database
    defaults: { _controller: BioversityOntologyBundle:Default:database }

b_o_browse_landrace:
    pattern:  /browse-landrace
    defaults: { _controller: BioversityOntologyBundle:Default:browseLandrace }

b_o_browse_cwr:
    pattern:  /browse-cwr
    defaults: { _controller: BioversityOntologyBundle:Default:browse_Cwr }

b_o_browse_trait:
    pattern:  /browse-trait
    defaults: { _controller: BioversityOntologyBundle:Default:browseTrait }

b_o_datasets:
    pattern:  /datasets
    defaults: { _controller: BioversityOntologyBundle:Default:datasets }

b_o_data_search:
    pattern:  /data-search
    defaults: { _controller: BioversityOntologyBundle:Default:dataSearch }

b_o_download_data:
    pattern:  /download-data
    defaults: { _controller: BioversityOntologyBundle:Default:downloadData }

b_o_request_data:
    pattern:  /request-data
    defaults: { _controller: BioversityOntologyBundle:Default:requestData }

b_o_contribute_data:
    pattern:  /contribute-data
    defaults: { _controller: BioversityOntologyBundle:Default:contributeData }
    
b_o_browse_slider:
    pattern:  /browse-slider
    defaults: { _controller: BioversityOntologyBundle:Default:browseSlider }

#----------------------------------------------------------------------------
#-----------------------ADMIN AREA-------------------------------------------
#----------------------------------------------------------------------------

b_o_dashboard:
    pattern:  /admin/dashboard
    defaults: { _controller: BioversityOntologyBundle:Default:dashboard }

b_o_edit_profile:
    pattern:  /admin/edit-profile
    defaults: { _controller: BioversityOntologyBundle:Default:editProfile }

#----------------------------------------------------------------------------
#-----------------------JSON RESONSE-----------------------------------------
#----------------------------------------------------------------------------

b_o_json_root_nodes:
    pattern:  /get-root-nodes
    defaults: { _controller: BioversityOntologyBundle:Default:JsonRootNode }

b_o_json_node_relations:
    pattern:  /get-node-relations/{nodeId}
    defaults: { _controller: BioversityOntologyBundle:Default:JsonNodeRelations }
    requirements:
        nodeId:  \d+

b_o_json_node_details:
    pattern:  /get-node-details/{nodeId}
    defaults: { _controller: BioversityOntologyBundle:Default:JsonNodeDetails }
    requirements:
        nodeId:  \d+

b_o_json_node_relation_in:
    pattern:  /get-node-relation-in/{nodeId}
    defaults: { _controller: BioversityOntologyBundle:Default:JsonNodeRelationIN }
    requirements:
        nodeId:  \d+

b_o_json_node_relation_out:
    pattern:  /get-node-relation-out/{nodeId}
    defaults: { _controller: BioversityOntologyBundle:Default:JsonNodeRelationOUT }
    requirements:
        nodeId:  \d+

b_o_json_node_relation_pager_in:
    pattern:  /get-node-relation-pager-in/{nodeId}/{page}
    defaults: { _controller: BioversityOntologyBundle:Default:JsonNodeRelationIN }
    requirements:
        nodeId:  \d+
        page:    \d+

b_o_json_node_relation_pager_out:
    pattern:  /get-node-relation-pager-out/{nodeId}/{page}
    defaults: { _controller: BioversityOntologyBundle:Default:JsonNodeRelationOUT }
    requirements:
        nodeId:  \d+
        page:    \d+