parameters:
#    bioversity_ontology.example.class: Bioversity\OntologyBundle\Example

services:
#    bioversity_ontology.example:
#        class: %bioversity_ontology.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
