bioversity_trait_browse_trait:
    pattern:  /trait/browse
    defaults: { _controller: BioversityTraitBundle:Trait:index }
    
bioversity_trait_browse_trait_filter:
    pattern:  /trait/browse/filter
    defaults: { _controller: BioversityTraitBundle:Trait:bestFilter }
    
bioversity_trait_json_trait_fields:
    pattern:  /trait/json/get/tag/fields/{word}
    defaults: { _controller: BioversityTraitBundle:Trait:jsonGetTagFields }