parameters:
#    bioversity_site_structure.example.class: Bioversity\SiteStructureBundle\Example

services:
#    bioversity_site_structure.example:
#        class: %bioversity_site_structure.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
