parameters:
    webservice_user_provider.class: Bioversity\SecurityBundle\Repository\User\WebserviceUserProvider

services:
    webservice_user_provider:
        class: "%webservice_user_provider.class%"