bioversity_slider_browse_slider:
    pattern:  /browse-slider
    defaults: { _controller: BioversitySliderBundle:Slider:browseSlider }
    
bioversity_slider_modal_slider:
    pattern:  /modal-slider/{node_id}
    defaults: { _controller: BioversitySliderBundle:Slider:modalSlider }

#----------------------------------------------------------------------------
#-----------------------JSON RESONSE-----------------------------------------
#----------------------------------------------------------------------------
bioversity_slider_json_root_nodes:
    pattern:  /get-root-nodes
    defaults: { _controller: BioversitySliderBundle:Slider:JsonRootNode }

bioversity_slider_json_node_relations:
    pattern:  /get-node-relations/{nodeId}
    defaults: { _controller: BioversitySliderBundle:Slider:JsonNodeRelations }
    requirements:
        nodeId:  \d+

bioversity_slider_json_node_details:
    pattern:  /get-node-details/{nodeId}
    defaults: { _controller: BioversitySliderBundle:Slider:JsonNodeDetails }
    requirements:
        nodeId:  \d+


#-------------Get
bioversity_slider_json_node_relation_in:
    pattern:  /get-node-relation-in/{nodeId}
    defaults: { _controller: BioversitySliderBundle:Slider:JsonNodeRelationIN }
    requirements:
        nodeId:  \d+

bioversity_slider_json_node_relation_out:
    pattern:  /get-node-relation-out/{nodeId}
    defaults: { _controller: BioversitySliderBundle:Slider:JsonNodeRelationOUT }
    requirements:
        nodeId:  \d+

        
#---------------Search
bioversity_slider_json_search_node_relation_in:
    pattern:  /search-node-relation-in/{nodeId}/{term}
    defaults: { _controller: BioversitySliderBundle:Slider:JsonSearchNodeRelationIN }
    requirements:
        nodeId:  \d+

bioversity_slider_json_search_node_relation_out:
    pattern:  /search-node-relation-out/{nodeId}/{term}
    defaults: { _controller: BioversitySliderBundle:Slider:JsonSearchNodeRelationOUT }
    requirements:
        nodeId:  \d+
    
bioversity_slider_partial_node_search:
    pattern:  /slider/partial/node/search
    defaults: { _controller: BioversitySliderBundle:Slider:partialNodeSearch }
    
bioversity_slider_json_node_search:
    pattern:  /slider/json/node/search
    defaults: { _controller: BioversitySliderBundle:Slider:JsonNodeSearch }
    
    
#----------------Pager
bioversity_slider_json_node_relation_pager_in:
    pattern:  /get-node-relation-pager-in/{nodeId}/{page}
    defaults: { _controller: BioversitySliderBundle:Slider:JsonNodeRelationIN }
    requirements:
        nodeId:  \d+
        page:    \d+

bioversity_slider_json_node_relation_pager_out:
    pattern:  /get-node-relation-pager-out/{nodeId}/{page}
    defaults: { _controller: BioversitySliderBundle:Slider:JsonNodeRelationOUT }
    requirements:
        nodeId:  \d+
        page:    \d+