parameters:
#    bioversity_user.example.class: Bioversity\UserBundle\Example

services:
#    bioversity_user.example:
#        class: %bioversity_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
